### ISSUE TITLE
Litmus Template | Footers

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#1]
@codextiny
Some of the email previews are not showing all of the footer. Is this because you built it with all instances of signatures? 
![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/55b82048-2386-4926-853b-c574a3522772)

Email previews that do not show footer are: 

1. Apple Mail 15 (macOS 12.0... 
2.  Apple Mail 16 (macOS 13.1... 
3. OL Office 365 (macOS 12.6.
4. Outlook 2016 (macOS 10.12..
5.  Outlook 2021 (Windows 10) 
6.iPad (Gen 7) (iOS 13.1) 
7. iPad (Retina) (iOS 13.1) 
8. iPad Air (Gen 4) (iOS 14.... 
9. iPad mini (Gen 6) (iOS 15... 
10. iPad Pro (10.5 inch) (iOS... 
11. iPhone 11 (iOS 14.2) 
12. iPhone 14 (iOS 16.4) 
13. iPhone SE (iOS 14.2) 
14.

**Comment by shannonbaldwin** [comment]
@codextiny I think the footers don't show in all previews because you have all scenarios listed in footer (loan officer, agent, both) with comments vs. actual test data. I think this will be solved once we test in SendGrid.

**Comment by codextiny** [comment]
@shannonbaldwin 

We have checked on our side, here is recorded video (https://www.loom.com/share/c842de36047f438e96b0c38108a063a8?sid=882a59f7-a45f-41f5-8b12-d10114e2afd2) .

It might be possible there is some issue with your device resolution can you please send us the recorded video, how are you testing? Then we will test email with your way.

**Comment by shannonbaldwin** [comment]
@codextiny Here is my recording. I tested on laptop and desktop device. Note I only made a copy of your template but did not change anything else.

https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/b2516e62-37b4-4ea6-b023-c78507c45095

**Comment by codextiny** [comment]
@shannonbaldwin 

Ahhh! it's not your screen's fault neither ours, its litmus's fault as you can see in video we inspect the page and adjust the visual window height and footer is showing, so don't worry footer will be fine in emails .

https://www.loom.com/share/c1ea21a5ac084bf697d3db96869e222b?sid=ed2155c9-4c87-40e8-8e10-5a5901c24661

**Comment by shannonbaldwin** [comment]
@codextiny woohoo!
