### ISSUE TITLE
Email Previews in Outlook instances

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#2]
@codextiny The logo and hub address variable + the header/subheader spacing is misaligned in all versions of the Outlook email versions. 
![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/eeae04b2-11af-4d31-b6cc-881db7ace9ad)

**Comment by codextiny** [comment]
can you please add some screenshots from the Figma file for reference 
screenshots will be helpful because we have followed the same spacings from your Figma file

**Comment by shannonbaldwin** [comment]
@codextiny The email previews below are the ones not rendering properly. You can see all other email previews are aligned as they should according to the[ Figma file,](https://www.figma.com/design/Nbc8bDKXEgxkfXHCGmqEFC/email-marketing?node-id=1041-62&t=N3H2qgPyNhfvMiuV-4) except for these three below and i think it is because these versions have a wider screen. 

1. Outlook 2021 (Windows 10)

2. Outlook 2021 120 DPI (Windows 10)

3. Windows 11 Mail (Windows 11)

<img width="573" alt="image" src="https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/80218923-f07c-4167-aa9a-6fbc39d8478e">

**Comment by codextiny** [comment]
@shannonbaldwin 

Same like this issue https://github.com/shannonbaldwin/Litmus-SG-Project/issues/1, we have checked on our side here is video (https://www.loom.com/share/d05f9dfba3044bb0bd4b16dfcaf628a0?sid=6242bdc2-9401-4fdb-9014-a5293182af71) please send us your way of testing in recorded video then we can check.

Thanks.

**Comment by shannonbaldwin** [comment]
@codextiny I tried to expand view like you did but cannot. Here is my recording for that. 

https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/3780305b-4e5e-4636-92ea-d440df76d8fd

**Comment by codextiny** [comment]
@shannonbaldwin 

yup, we found the mistake as we mentioned you about logos to export them in exact size, same for banner and other images please export image from design in exact size and upload it, hopefully everything will be fine .
