### ISSUE TITLE
Consumer Invitation Campaign

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#29]
@codextiny Please see[ updated hero images ](https://docs.google.com/document/d/109zA7xpkM9qrVQnPsP5Syu528YMxSXvX03tyVcOiprE/edit)for the 4 email campaign as well as icon updates, similar to the opt-out campaign.

**Comment by shannonbaldwin** [comment]
@codextiny
CONSUMER Invitation Campaign Email 1 - Homeownership made easy (I renamed these)

1. Decrease spacing near first arrow above bullet point to be same spacing below (Second arrow)![image](https://github.com/user-attachments/assets/6b6c9eae-fb38-4d2e-b615-b9e4342d87df)

2. Please update CTA button to the blue I updated here for ALL templates![image](https://github.com/user-attachments/assets/4f4d8cbb-413f-4981-8b08-718bab68c65c)

3. I noticed a typo in the footer. I updated most of the emails in this campaign but please note this when updating in other areas
![image](https://github.com/user-attachments/assets/5704d85d-b384-4c63-b1ca-0ae863a6e598)

**Comment by shannonbaldwin** [comment]
@codextiny
CONSUMER Invitation Campaign Email 2 - Your home value is ready1. Decrease spacing here and please make sure it does not effect mobile view.![image](https://github.com/user-attachments/assets/ac24ee28-c0a6-4c03-b738-81f1a934f7f0)

**Comment by shannonbaldwin** [comment]
@codextiny
CONSUMER Invitation Campaign Email 3 - DIY or hire local: Your ultimate resource portal

1. Decrease spacing![image](https://github.com/user-attachments/assets/b1c18277-3728-4c1a-9f20-9105f98f65bb)

**Comment by shannonbaldwin** [comment]
@codextiny
CONSUMER Invitation Campaign Email 4 - Browse local referrals to get repairs done faster

1. Update icons based on figma file![image](https://github.com/user-attachments/assets/3928b2ed-1db5-41cb-ad8a-94d580b94550)

**Comment by codextiny** [comment]
Hi @shannonbaldwin 

fixed all spacing issues, please check.
"Please update CTA button to the blue I updated here for ALL templates", confused about this point, can you please explain which color you want on your buttons on all templates, can you please provide color code.

and for icons module we will start working after getting confirmation.

Thanks,

**Comment by codextiny** [comment]
@shannonbaldwin 

One thing need to mention here about your icons mobile layout, as per our previous experience with other clients emails, when we break table layout on mobile view with custom css, sometimes its not working on some email clients so first we will apply updated layout on one of your template then you will check on all email clients and give us go ahead to implement on other emails, then we will apply same layout to other emails.

Thanks, 
Codextiny

**Comment by shannonbaldwin** [comment]
@codextiny 
1. All 4 templates have been finalized with spacing, CTA button placement, updated icons, signature layout update, and finalized content changes. I have created a new Figma page with these 4 templates with all of these updates for your reference. I also made comments on each section where updates have been made to try and make it easy for your team. [Figma page can be found here.](https://www.figma.com/design/pNB8IB2Eiq5JRmvOuPJVEa/Marketing-Creative?node-id=2061-14952)
2. We have copied over the existing 4 templates into the Live inHere instance of Sendgrid. Once your team makes updates, we will switch these over to the active templates internally. Below are the credentials to that Sendgrid account (you will need authy code) but if easier, you can update the templates in the main account and we can copy them over. 
**inhere-sendgridadmin@milestones.ai
Crayon-Postnasal-Numerate9-Strewn-Ride-Subsoil**
![image](https://github.com/user-attachments/assets/5e08658e-172f-4e63-ae1b-7b1f74004ed1)
![image](https://github.com/user-attachments/assets/03e9b146-c357-4822-95a2-ba6d4c94706e)3.

**Comment by codextiny** [comment]
Hi @shannonbaldwin 

![image](https://github.com/user-attachments/assets/d30fe7ec-d86e-4599-aa1a-bf60c6aa3360)
![image](https://github.com/user-attachments/assets/6e957824-dd89-43c0-a011-ccdf361baf37)
![image](https://github.com/user-attachments/assets/67ab2c73-2408-4e53-aaf5-dc3cf011a216)

- We have seen new figma design, need some confirmation what if both real estate or loan officer enabled then which layout we should follow because you just made design with single real estate agent?
- And we have to follow the icons new layout, agents new layout, header/footer Logo and spacing on all email campaigns including 4 emails and previous 17 emails, right ?

Thanks

**Comment by codextiny** [comment]
@shannonbaldwin 

one more thing need to mention here that you have used poppins font family on new email templates in figma and adjusted the spacing and font sizes accordingly, please use "Lato" font family which is tested and you guys suggested us to use because its tested from your side. please change font from Popping to Lato in figma file then we can adjust the spacing accordingly.

and also another thing, do we need to check/re-adjust the font sizes and font weights on all templates, it will take time and its equal to create new template, please confirm then we will give you the estimate accordingly.

![image](https://github.com/user-attachments/assets/31562aff-1016-41e4-8459-930d71244317)

Thanks

**Comment by shannonbaldwin** [comment]
@codextiny
In response to this question below,  yes, this will apply to all 17 emails as well. 

And we have to follow the icons new layout, agents new layout, header/footer Logo and spacing on all email campaigns including 4 emails and previous 17 emails, right ?

**Comment by shannonbaldwin** [comment]
@codextiny In response to the question below, we will stack instances of loan officer, versus side by side in case there are really long agent or loan officer names. I updated the first template in Figma for example.

**Comment by codextiny** [comment]
@shannonbaldwin 

got it, what about font family, font size and font weight ??

**Comment by shannonbaldwin** [comment]
@codextiny All the same fonts, etc for all templates so they are standardized.

**Comment by shannonbaldwin** [comment]
@codextiny Ideally, would love the profiles to be side by side but do you think that is risky for longer names, even though we reduced headshot size?

**Comment by codextiny** [comment]
> @codextiny Ideally, would love the profiles to be side by side but do you think that is risky for longer names, even though we reduced headshot size?

our suggestion, make them vertically, because on some email clients we have shorter width, so vertical layout will be fine .

![image](https://github.com/user-attachments/assets/5d42b113-739c-4cac-95f7-cfa51c1aa467)
This is perfect.

**Comment by shannonbaldwin** [comment]
@codextiny Figma updated to Lato font.

**Comment by codextiny** [comment]
> @codextiny In response to this question below, yes, this will apply to all 17 emails as well.
> 
> And we have to follow the icons new layout, agents new layout, header/footer Logo and spacing on all email campaigns including 4 emails and previous 17 emails, right ?

did you create figma for other 17 templates for us to follow the spacing because every template have different content??

@shannonbaldwin

**Comment by codextiny** [comment]
> > @codextiny Ideally, would love the profiles to be side by side but do you think that is risky for longer names, even though we reduced headshot size?
> 
> our suggestion, make them vertically, because on some email clients we have shorter width, so vertical layout will be fine .
> 
> ![image](https://private-user-images.githubusercontent.com/113863175/348770742-5d42b113-739c-4cac-95f7-cfa51c1aa467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTkxOTEsIm5iZiI6MTcyMTA1ODg5MSwicGF0aCI6Ii8xMTM4NjMxNzUvMzQ4NzcwNzQyLTVkNDJiMTEzLTczOWMtNGNhYy05NWY3LWNmYTUxYzFhYTQ2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxNTU0NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmEzYmU3YjkzOTg1YzM3NWYxOGFmYzJmNzUyZTlkZjYzMTFkMTRlODExNjIzNjY2NjcyODEzNDljYTA1NzU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g71HTcjLtcNbqvxFaRMTKfcPSDVpODc_tzDKr4ImUs4) This is perfect.

please respond to this as well?

@shannonbaldwin

**Comment by shannonbaldwin** [comment]
@codextiny Yes, on Figmas for 17 templates.

**Comment by shannonbaldwin** [comment]
@codextiny vertical is fine

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/364711c4-dc1d-40aa-b597-7678b01fd219)

shanon, can you please use same spacing from top/bottom of this "Questions about your portal? Feel free to contact me.  " line and also from top/bottom of separator, or i guess you are working on template's spacing?

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/4def1bb0-a2aa-4028-bc75-e7550adf05f4)

We noticed you are still making changes to the content section in figma design can you please tell us when you will be finished making these changes so we could do exactly the same in your send grid templates because we have made the changes to the bullet points section and now you have changed the spacing again. We don't mind changing them again but we will let you finish them first then we will start making changes accordingly.

**Comment by shannonbaldwin** [comment]
@codextiny I am DONE! Sorry!

**Comment by codextiny** [comment]
@shannonbaldwin 

No problems we didn't stopped working we worked on the signature module meanwhile.

**Comment by shannonbaldwin** [comment]
@codextiny I made one minor spacing change directly in one of the template so no issues there. 

Question only: Are you able to adjust mobile views only in HTML?

**Comment by shannonbaldwin** [comment]
@codextiny Please update emails 2, 3, and 4 to same spacing as email 1 after "Hi [User First Name]."

Email 1 preview which 2, 3, and 4 templates should follow:<img width="687" alt="image" src="https://github.com/user-attachments/assets/67f13cf9-6fc1-43d8-913d-123087a3baaa">

Email 2, 3, and 4 previews that need to be updated for reference:
<img width="635" alt="image" src="https://github.com/user-attachments/assets/17c56bcc-7a11-4a19-a191-5437ddec7e89"><img width="714" alt="image" src="https://github.com/user-attachments/assets/cb103ff8-13e4-45e6-8c19-7520f471aea4"><img width="670" alt="image" src="https://github.com/user-attachments/assets/adfd0253-c532-422d-ba82-5db9b7245a11">

**Comment by shannonbaldwin** [comment]
@codextiny 
I updated one minor punctuation error directly in template so no issues there. 

Final edits needed ([and also commented in Figma so it is easier to see](https://www.figma.com/design/pNB8IB2Eiq5JRmvOuPJVEa/Marketing-Creative?node-id=2061-14952)). 
1. Adjust spacing of "No, thank you. I'm not interested" line according to updated Figma file. 
2. Underline "No, thank you. I'm not interested." so that it is apparent it is a link.
3. Please see mobile adjustment requests [in Figma file on the mobile file. 
](https://www.figma.com/design/pNB8IB2Eiq5JRmvOuPJVEa/Marketing-Creative?node-id=2061-14952)

**Comment by codextiny** [comment]
HI @shannonbaldwin 

All of the changes above mentioned and in figma file are done from our side, please check.

and as per our understanding, mobile icons layout is fine the way it is, so we dont need to update it according to figma ..

![image](https://github.com/user-attachments/assets/fdd9510c-3404-48fb-9747-6a452aa364c7)

Thanks

**Comment by codextiny** [comment]
@shannonbaldwin 

Updated content of first email, please check

**Comment by shannonbaldwin** [comment]
@codextiny Is there a way to adjust the padding for mobile so that the lines break into two? I see you added padding but ideally, I would want it to look like the screenshot below. ![image](https://github.com/user-attachments/assets/520f01b2-2961-4f3c-9f1a-979a436ef2a1)
![image](https://github.com/user-attachments/assets/12243704-381c-4256-930c-3d6a11b99ab2)

**Comment by codextiny** [comment]
@shannonbaldwin 

We already added enough spacing according to mobile's smaller size, if we will increase the spacing then on smaller devices your content looks like a vertical line, 
See screenshot below. and we cannot be dependent on media-queries too much because some older emails clients doesn't support media queries . 

![image](https://github.com/user-attachments/assets/536355d0-8c75-42dc-9a8f-24e1b358c2a1)

Thanks,

**Comment by shannonbaldwin** [comment]
@codextiny Is Sendgrid mobile view reliable? i was going off of my iphone view.

**Comment by codextiny** [comment]
@shannonbaldwin 

Basically sendgrid's preview is browser based and it support everything, every single css, but we should keep in mind about every email client, because some supports every css and some not, that's why we choose to use simple css which will work on every email client.

Hope you got my point.

Thanks

**Comment by shannonbaldwin** [comment]
@codextiny We tested the first template in-product because this campaign is now live. Please see below for errors:

1. We need to add padding above first sentence and below the header if no first name exists. 
![image](https://github.com/user-attachments/assets/716e2c02-e813-40b7-8d1b-1cccb0e29b04)
2. If no phone number, we need to remove the phone icon.
![image](https://github.com/user-attachments/assets/776ff5ce-69d9-4520-b5ae-7acfe30a3100)

**Comment by codextiny** [comment]
@shannonbaldwin 

please share template id, do we need to update it on all other templates if yes then please let us know which templates?
if you will provide us ids that will be more easy for us.

**Comment by shannonbaldwin** [comment]
@codextiny The live campaigns are on a timed cadence so I am not able to see those live. I would suggest that the same code is applied to all 4 templates if not in there already. 

Template ID: d-cd32f2e7f8e1463f94814b2a3c7ec5ca 
Template ID: d-8af666b64bac468e8ac15e9c87355b48 
Template ID: d-4f4eff1294474c7aa65e4335cbc5f28e 
Template ID: d-4469d6d9e8c44637a9e24a843d6f608c

**Comment by codextiny** [comment]
@shannonbaldwin 

We have applied all changes on above mentioned templates, please check.
