### ISSUE TITLE
Logo Best Practices 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#3]
@codextiny I think I need to reset the logo specs in Figma because as you can see in my email version in Litmus (that I copied from yours), the logo is too big on certain email previews. Is there a best practice for this that I can follow so that they pass the Litmus test?

<img width="285" alt="image" src="https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/861b850f-38d2-4476-bc37-4f4ac2a18f7f">
<img width="262" alt="image" src="https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/45d527d3-7177-4568-a85c-69d233d39124">

**Comment by codextiny** [comment]
@shannonbaldwin 

here we can't apply fixed height, width because its not good practice and also not good for your logo because we don't know in which shape you will use logo in future. and max width/height will not work on some email clients.

So, its best for you to export exact height/width logo and use in email template.

**Comment by shannonbaldwin** [comment]
@codextiny Yes, you are right and I thought so. This is something internally we will have to implement. I just tested the exact size logo specs and it works great.

**Comment by shannonbaldwin** [comment]
@codextiny I noticed the header logo in the FUTURE Invite Campaign 1 - (Clone for Testing Codextiny) has the wrong dimensions as the placeholder which confused me but it looks like the code has the right dimensions.

<img width="685" alt="image" src="https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/1eb5e9b5-6187-4110-bb95-0ef530806744">

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/113863175/d157d1a9-5da7-4107-9231-d5775dee1981)
![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/113863175/3d7b4934-5de1-4828-96bd-f1e3f003b5e0)

We have used the variable which brings the logo from your library, no worries we didn't add any dimensions on image directly, you can change ...
