### ISSUE TITLE
Consumer Intro Campaign (17 emails)

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#30]
@codextiny

**Email 1**

See spacing on CTA button on desktop. Looks fine on mobile.
![image](https://github.com/user-attachments/assets/57e8aaea-7d0d-48b1-906f-28c313f778bc)

**Comment by shannonbaldwin** [comment]
@codextiny All emails excluding 2,3 and 4 all have issue below. 

1. Underline now showing on desktop
![image](https://github.com/user-attachments/assets/1a999ebe-c26b-4d61-be5f-f60e9667ad38)

**Comment by shannonbaldwin** [comment]
@codextiny 
Email 15

Spacing issue: 
![image](https://github.com/user-attachments/assets/e9038255-7f4a-47cc-9911-5d789db632bc)

**Comment by codextiny** [comment]
> @codextiny
> 
> **Email 1**
> 
> See spacing on CTA button on desktop. Looks fine on mobile. ![image](https://private-user-images.githubusercontent.com/167017886/349656651-57e8aaea-7d0d-48b1-906f-28c313f778bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTAxNjIsIm5iZiI6MTcyMTI0OTg2MiwicGF0aCI6Ii8xNjcwMTc4ODYvMzQ5NjU2NjUxLTU3ZThhYWVhLTdkMGQtNDhiMS05MDZmLTI4YzMxM2Y3NzhiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMDU3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjNjN2ZkNWMxZGYwZTk3MjQwMjFlMThlMWQ1MmJjM2U0YmZjMGYxZGNjMzRhMTE3Mjk3NGZiZjVkN2JmODdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B-EkicAaz1m2Ja8PUgmBZ4F7HsufP9cuY65Q6lVjJXA)

Fixed!

**Comment by codextiny** [comment]
> @codextiny Email 15
> 
> Spacing issue: ![image](https://private-user-images.githubusercontent.com/167017886/349676103-e9038255-7f4a-47cc-9911-5d789db632bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTAxNjIsIm5iZiI6MTcyMTI0OTg2MiwicGF0aCI6Ii8xNjcwMTc4ODYvMzQ5Njc2MTAzLWU5MDM4MjU1LTdmNGEtNDdjYy05OTExLTVkNzg5ZGI2MzJiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMDU3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWRjNzFjZTdhOTg2OTg4MjJmYTFmMGNmN2QyMTc5MWVhZDg2MTVhM2YzODk4OGFjNmM3YWUzMTUzNTgyN2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dVO2US3UJhUkMkIQ8xrVJ8woEHNKsOzsghJjyzrdi2Q)

Fixed!

**Comment by codextiny** [comment]
> @codextiny All emails excluding 2,3 and 4 all have issue below.
> 
>     1. Underline now showing on desktop
>        ![image](https://private-user-images.githubusercontent.com/167017886/349670495-1a999ebe-c26b-4d61-be5f-f60e9667ad38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTAxNjIsIm5iZiI6MTcyMTI0OTg2MiwicGF0aCI6Ii8xNjcwMTc4ODYvMzQ5NjcwNDk1LTFhOTk5ZWJlLWMyNmItNGQ2MS1iZTVmLWY2MGU5NjY3YWQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMDU3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWJkNzU1YzA1N2EzZjM0MzQ2NmNjN2E5NmY4Yjc0OTUzYzA5OTEyMzA5OTg0MmZhZTAxY2E5OGM2ZGViOGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1YdK-AazwKI1fAQnBvp-jlwGqCxpwDt4M7wMosU0q-Y)

can you please elaborate, unable to understand, you want underline under "No, thank you. I’m not interested." or want us to remove ??

**Comment by shannonbaldwin** [comment]
@codextiny The underline feature should be appearing there (See screenshot) but it is not appearing on desktop, only mobile. Emails 2,3, and 4 show the underline on desktop but all others do not. We need to it to appear on desktop, just like the others.![image](https://github.com/user-attachments/assets/52dee3a8-fe56-41af-a25e-a23d3339c156)

**Comment by codextiny** [comment]
@shannonbaldwin 

Email 5
![image](https://github.com/user-attachments/assets/e7df9c7a-ea97-4166-85e3-87685118c281)

Email 6
![image](https://github.com/user-attachments/assets/adb366d0-5677-4d78-94f7-54bfd09e648d)

its working fine for us, can you please tell us on which device or browser or email client you are checking, or its not showing on sendgrid preview...

**Comment by shannonbaldwin** [comment]
@codextiny Gmail in chrome.

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/49c9fbde-5947-4a7f-bcc2-6b97ab42e68d)

![image](https://github.com/user-attachments/assets/babac60c-acea-48c0-9ff8-6f0bc46f07a4)

its because of you guys didn't create data variable for "consumer_hoh_opt_out" this, and that's why anchor's href is empty and gmail treated it like text.

Please create data variable and it will work fine.

Thanks.

**Comment by shannonbaldwin** [comment]
@codextiny Ah! Got it. 

@ned Can you add so I can finish testing these?

**Comment by shannonbaldwin** [comment]
Template ID: d-fa7dfd37febf44a4b4a4244e41c1bfd2@codextiny I am still seeing the spacing issue in Email 8 (. ![image](https://github.com/user-attachments/assets/4f0d692f-909e-42cb-8ed5-2a88af2d0e06)

**Comment by shannonbaldwin** [comment]
@codextiny Regarding your note above about a variable missing, see screenshot below. This is email 8 (which is not showing the underline feature in desktop) but it does have the variable there. 
![image](https://github.com/user-attachments/assets/abd5718f-9222-4b37-9193-d9479f795d8c)

**Comment by codextiny** [comment]
``

> @codextiny Regarding your note above about a variable missing, see screenshot below. This is email 8 (which is not showing the underline feature in desktop) but it does have the variable there. ![image](https://private-user-images.githubusercontent.com/167017886/350068644-abd5718f-9222-4b37-9193-d9479f795d8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzI1NTUsIm5iZiI6MTcyMTMzMjI1NSwicGF0aCI6Ii8xNjcwMTc4ODYvMzUwMDY4NjQ0LWFiZDU3MThmLTkyMjItNGIzNy05MTkzLWQ5NDc5Zjc5NWQ4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxOTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzIxY2QzMDYzZDQ4YTU3NjU5NjA2ZTdiNjI5Mjk3ODE5YmRmMTViNTY3MjFjMzVhMjk2YzkwOWMyZGNjMzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x2rH8mo6dJisTuHlqlT-uXOUtzC0EfHTwNzEt2BJPrM)

@shannonbaldwin 

Variable is there but the variable and value of variable is not defined under  "{ } Test Data", so you need to define the variable and value inside test data tab. please search "consumer_hoh_opt_out" under test data tab then things will be more clear.
We just added the variable and value please see below screenshot.

![image](https://github.com/user-attachments/assets/359f29e3-9455-4dc6-a4d8-227014c5d089)

Thanks

**Comment by codextiny** [comment]
> Template ID: d-fa7dfd37febf44a4b4a4244e41c1bfd2@codextiny I am still seeing the spacing issue in Email 8 (. ![image](https://private-user-images.githubusercontent.com/167017886/350064065-4f0d692f-909e-42cb-8ed5-2a88af2d0e06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzI1NTUsIm5iZiI6MTcyMTMzMjI1NSwicGF0aCI6Ii8xNjcwMTc4ODYvMzUwMDY0MDY1LTRmMGQ2OTJmLTkwOWUtNDJjYi04ZWQ1LTJhODhhZjJkMGUwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxOTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjQyM2Q2N2Q5ZGY0ZWQ0ZTM5NWYxOGRkMjNhMmU0NzZiMTAzY2JmYmZhZGUyNmE5M2M1YTg2Y2YyMTdiNThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xfwo8P-_0P6UCDWC3LxlweR9IvfpDxRmkULGVh52STI)

Fixed, please check

**Comment by shannonbaldwin** [comment]
@codextiny I figured out what the issue is here. The padding is inconsistent in these templates. I tested email 1 and adjusted padding to email 2 and it worked. Can you please adjust all templates?

**Comment by shannonbaldwin** [comment]
@codextiny We've found that the logo in the header isn't always using the same expected value. Sometimes it's {{organization_logo_simple}} instead of {{hub_organisation_logo_simple}}. Can you please update all logos in header with the same variable " {{hub_organisation_logo_simple}}?"

**Comment by codextiny** [comment]
> @codextiny I figured out what the issue is here. The padding is inconsistent in these templates. I tested email 1 and adjusted padding to email 2 and it worked. Can you please adjust all templates?

@shannonbaldwin 

can you please provide the screenshot, what exactly you updated, which space we need to readjust??|

Thanks

**Comment by shannonbaldwin** [comment]
@codextiny Something happened to template 11?d-af66df3625ab4caf8a3a900cbb44c9d3

**Comment by codextiny** [comment]
@shannonbaldwin 
We haven't made any changes to template 11.

**Comment by shannonbaldwin** [comment]
@codextiny See below in email 1. I have already indicated which emails have spacing issues above. 
![Screenshot 2024-07-24 at 1 28 14 PM](https://github.com/user-attachments/assets/b00676ea-6fad-446b-beb9-21f886cd3fbd)

**Comment by codextiny** [comment]
> @codextiny We've found that the logo in the header isn't always using the same expected value. Sometimes it's {{organization_logo_simple}} instead of {{hub_organisation_logo_simple}}. Can you please update all logos in header with the same variable " {{hub_organisation_logo_simple}}?"

@shannonbaldwin 

do we need to update header logo of all 17 templates with "{{hub_organisation_logo_simple}}" variable, right, did you add the variable in test data tab and upload the logo ??

**Comment by shannonbaldwin** [comment]
@codextinyThe test data tab does not matter. Yes, we need that variable on all templates.

**Comment by codextiny** [comment]
> @codextiny See below in email 1. I have already indicated which emails have spacing issues above. ![Screenshot 2024-07-24 at 1 28 14 PM](https://private-user-images.githubusercontent.com/167017886/351831285-b00676ea-6fad-446b-beb9-21f886cd3fbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NTQzNjYsIm5iZiI6MTcyMTg1NDA2NiwicGF0aCI6Ii8xNjcwMTc4ODYvMzUxODMxMjg1LWIwMDY3NmVhLTZmYWQtNDQ2Yi1iZWI5LTIxZjg4NmNkM2ZiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQyMDQ3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWRiYzg3OGJjYzA4ZDgxMGM4ZTcxZDdmMWQ1NDljNjM3YTRiZDVjOTA0NTJiZmYzYWQ2MTBkY2JkODIxNzE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zOa3fH2cNcsuLCPYkmN5SNlQb2G8McqUtcTomYkSUXY)

@shannonbaldwin 

Spacing looks fine and according to your figma design, is there any spacing issue with specific email client that you are facing or you want us to increase the spacing in actual sendgrid preview ??

![image](https://github.com/user-attachments/assets/b0089a52-647f-40cd-871b-8f7c8d18b20c)


Thanks

**Comment by codextiny** [comment]
> @codextinyThe test data tab does not matter. Yes, we need that variable on all templates.

one thing need to confirm, do you want us to add both logos variable with condition, if yes then which will be the priority.
or if you want us to replace directly "{{hub_organisation_logo_simple}}" variable with current.

and test data matter because if variable value is empty it shows broken image in preview .

Please do let us know what exactly you want ?

Thanks

**Comment by codextiny** [comment]
@shannonbaldwin 

can you please provide us correct figma for top space of cta and we will apply on all other 17 templates, or 1st template spacing is fine for you the we will apply exact first template's spacing on other 16.

Thanks
