### ISSUE TITLE
Pro Invitation Campaign 1

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#31]
@codextiny

All emails:

Underline under "Book a Meeting" is not showing. Can you embed this link and maybe that will fix the issue? 
https://calendly.com/alicia-liveinhere/meet-with-alicia-live-inhere

![image](https://github.com/user-attachments/assets/95372acd-036d-4b83-9cbd-fbdc806c9067)

**Comment by shannonbaldwin** [comment]
@codextiny
Template ID: d-304ae56afac848949e1991a6fe76ef54

Please double check font size in header. It looks larger than others?
 ![image](https://github.com/user-attachments/assets/025a5e2b-2020-4d3a-a9e6-d3c19ca6efd9)

**Comment by shannonbaldwin** [comment]
@codextiny 
Please update emails 1, 2, and 3 with space spacing after "Hi First Name" as the 6 other templates. I think the bullet points threw off the original spacing. 

Correct spacing:
 ![image](https://github.com/user-attachments/assets/c56c3e76-1788-466d-b5e3-38d95abea407)

Incorrect spacing: 
![image](https://github.com/user-attachments/assets/c322cc84-9fff-4217-add1-7d44b9d61815)

**Comment by codextiny** [comment]
@shannonbaldwin 

All above mentioned points are done, please check .
