### ISSUE TITLE
Pro Campaign V2.3

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#33]
Please update subject lines in emails 3-9 with if/then first name statements. See email 1 as the example.

**Comment by codextiny** [comment]
@shannonbaldwin 

Please provide template id of email 1.

**Comment by codextiny** [comment]
@shannonbaldwin 

and please provide Screenshot for better understanding

**Comment by shannonbaldwin** [comment]
@codextiny
Template ID: d-0d7dd5c33f794217a3bbf3200b04ddb2 
![Screenshot 2024-08-01 at 3 07 12 PM](https://github.com/user-attachments/assets/fed3caf9-7979-4631-b5c5-73462ba29179)

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/610c3237-0a4b-4c13-8125-cacd137e8b47)

can you please confirm which one is 3rd and 9th ??

**Comment by shannonbaldwin** [comment]
@codextiny Here are the IDs for templates 3 through 9 where I need help with the subject lines and if/then statements.

Want more warm referrals, {{user_first_name)? 
D-304ae56afac848949e1991a6fe76ef54


{user_first_name, deepen your  relationships with timely insights
D-b5dc6d1c3a724ed3a9ebba6658aa73eb


{{user_first_name}}, revolutionize the value of the real estate agent 
D-e20cfe0da3f5488bb7d1bf5691205f00


Stop being a transactional agent
D-400e486102fc45dc8b5a36611cf754a6


{First Name}, leverage your network to 10x your results 
D-69f491a3e688416ba95bc59069f020a5


[[RE Pro First Name], want to have clients for life?
D-87b1c874c29a4410bf3656a37471128d


{{user_first_name}}, what's the value in becoming a trusted home advisor? 
d-63700940fc3c447e9233187ccb14805f

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/91d61c3c-02a0-4b0b-a9f2-bec41c69ae34)

- Do we need to update this subject on all of three variations.?
- do we need to apply if condition on all variable in subjects, like {{user_first_name}}, {{Re Pro First Name}} ??
- We will make sure the capitalization is correct through conditions...


Please respond accordingly

**Comment by shannonbaldwin** [comment]
Just V2.3. I can copy the rest over. 

Yes, if condition for all subjects but with variable “user_first_name”

**Comment by codextiny** [comment]
@shannonbaldwin 

Subjects updated, please check

**Comment by shannonbaldwin** [comment]
@codextiny Template ID: d-304ae56afac848949e1991a6fe76ef54 
Remove comma when no first name

<img width="1440" alt="Screenshot 2024-08-01 at 5 19 39 PM" src="https://github.com/user-attachments/assets/2b2cba50-2c9a-4cbb-b8c3-b451cb00c160">

**Comment by shannonbaldwin** [comment]
@codextiny This template is missing the condition in subject. D-400e486102fc45dc8b5a36611cf754a6

**Comment by codextiny** [comment]
> @codextiny Template ID: d-304ae56afac848949e1991a6fe76ef54 Remove comma when no first name
> <img alt="Screenshot 2024-08-01 at 5 19 39 PM" width="1440" src="https://private-user-images.githubusercontent.com/167017886/354398371-2b2cba50-2c9a-4cbb-b8c3-b451cb00c160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NTM4NDgsIm5iZiI6MTcyMjU1MzU0OCwicGF0aCI6Ii8xNjcwMTc4ODYvMzU0Mzk4MzcxLTJiMmNiYTUwLTJjOWEtNGNiYi1iOGMzLWI0NTFjYjAwYzE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQyMzA1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWEzM2ZmN2IwYzdkYTk3MTA0NzE0NWU4YzU5MmU0MmYyMWFlN2Q3OGFlNGMxNmRiODA1ODMyNTgwYjRjZWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TFaSgD_6fpz0pyW-wop-Nd9B2_HInXTquPzHHFqo26Q">

Done, please check

**Comment by codextiny** [comment]
> @codextiny This template is missing the condition in subject. D-400e486102fc45dc8b5a36611cf754a6


i think you forgot to mentioned above the first name .


Stop being a transactional agent
D-400e486102fc45dc8b5a36611cf754a6

Where we can add first name condition??

**Comment by shannonbaldwin** [comment]
@codextiny I fixed this so good here!
