### ISSUE TITLE
Introduction Campaign Footer Image Not Displaying Correctly

### ISSUE THREAD

**Issue by NedHOAI** [shannonbaldwin/Litmus-SG-Project#34]
Introduction campaign footer is not being contained within a circular border.

Screenshot of the issue:
![image](https://github.com/user-attachments/assets/f42282c9-407d-4ff8-a316-07c7c32d31c1)

For testing reference, this is the image used for testing:
https://api.uat.milestones.softia.works/storage/uploads/users/59e85613-9aa3-4de8-88df-5c9dfdeb974f/Feb24/21224_161038_65ca42fe332709.05801077_image-reposition.png

In Figma, please note that the template should force a circular shape for the image. This is meant to provide consistency, as pros will not be expected to upload photos in a specific format: 
![image](https://github.com/user-attachments/assets/62bdef5a-8878-4b30-a771-e453c77454ad)

Please ignore the formatting issue with the phone number; this is a dev issue that will be resolved with corrected variables.

**Comment by shannonbaldwin** [comment]
@codextiny

**Comment by codextiny** [comment]
@shannonbaldwin 

Adjusted image in code but our suggestion is to make/crop image rounded from design because sometime border radius not working on some email clients.

**Comment by shannonbaldwin** [comment]
@codextiny We will look into the design. Can you please update a max and min width and height according to Figma design for the company logos?
![image](https://github.com/user-attachments/assets/62410d49-95e8-4473-96e1-373c6a54a114)

**Comment by codextiny** [comment]
@shannonbaldwin 

Done, please check
