### ISSUE TITLE
Dynamic Template to a Marketing Single Send 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#35]
@codextiny 

Is it possible to copy the dynamic templates from Pro Invite V2.2 that you added in SendGrid to marketing single sends? I tried copying a template from V2.3 and removing the variables. You can see that single send in Marketing > Single Sends > FMLS Template Test.  It seemed to work but I want to make sure there are no issues with that? The reason in doing this is to bypass testing with dev and do this manually due to time constraints for a large customer. 

Ideally, I would love to use our new template for these single sends. Please let me know.

**Comment by codextiny** [comment]
@shannonbaldwin 

we are sorry, we can't help you here, we need template id or url or some screenshot for better understanding, what exactly you want ..??

**Comment by shannonbaldwin** [comment]
@codextiny I want to take each email of the Untitled Version (V2.2) campaign you added into SendGrid and make them single marketing sends with no variables. Template ID: d-0d7dd5c33f794217a3bbf3200b04ddb2 

![image](https://github.com/user-attachments/assets/645045d8-b362-421c-a522-d890ff5849c8)

If you check here (see below), you can see I tried to copy and paste the first template Template ID: d-0d7dd5c33f794217a3bbf3200b04ddb2 of V2.2 as a marketing single send called "FMLS TEMPLATE TEST". Can you confirm the template will still work the same? If so, I would love if you could help make all 9 templates of this V2.2 campaign into marketing single sends.

![image](https://github.com/user-attachments/assets/444ab3f3-3419-466a-be72-952995c0a6a1)![image](https://github.com/user-attachments/assets/a12aa903-20b9-4bb7-b431-6d8003d28626)

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/d597d840-5d12-4ef1-a696-829ab0efb9a5)

Marketing tab not showing for us, i guess some permission issue, can you please check ??

**Comment by shannonbaldwin** [comment]
@codextiny You now have marketing access

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/1309d36b-bd45-4853-af36-9311f47a23aa)

![image](https://github.com/user-attachments/assets/8039ee5f-edd1-4a8c-ae96-b705a03f1449)

We are unable to create/save single send, can you please check whats the issue, i guess some issue with permissions ...

**Comment by shannonbaldwin** [comment]
@codextiny I just made you an admin. That should do the trick.

**Comment by codextiny** [comment]
@shannonbaldwin 

We have removed the variables, can you please check and let us know if you have any problem.
https://mc.sendgrid.com/single-sends/94896f7e-5070-11ef-bf23-961ead127411/editor

Thanks

**Comment by shannonbaldwin** [comment]
@codextiny The only question is how to remove the hero image from being linkable. See screenshot of when you click on hero image.
![image](https://github.com/user-attachments/assets/4bf1afc4-ba0a-445e-adb6-f43ebb65057c)

**Comment by codextiny** [comment]
> @codextiny The only question is how to remove the hero image from being linkable. See screenshot of when you click on hero image. ![image](https://private-user-images.githubusercontent.com/167017886/354723264-4bf1afc4-ba0a-445e-adb6-f43ebb65057c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MzI3NjQsIm5iZiI6MTcyMjYzMjQ2NCwicGF0aCI6Ii8xNjcwMTc4ODYvMzU0NzIzMjY0LTRiZjFhZmM0LWJhMGEtNDQ1ZS1hZGI2LWY0M2ViYjY1MDU3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQyMTAxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2JjMDNmYjBjNjkyZDc4MWY5OTc3OWNmNDkzMGFlYWNlMjgxODIxOTdiZTA0MmIzMDRkZWU5MWRlZDY4ODBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.swlgh8WDRhCurjDH3LgCJFzHESONSMaAeq2rMgWj-tw)

@shannonbaldwin 
i guess you guys have already figured it out and removed the "a" tag from image, "a" tag is used to make something linkable..
