### ISSUE TITLE
Bottom Spacing on Templates 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#36]
@codextiny 
Template ID: d-cd32f2e7f8e1463f94814b2a3c7ec5ca, "Untitled Version"

Can we make sure the bottom spacing in this template is consistent with the top? See my Gmail email screenshots below. If you can please update that and show me where to make the update in HTML, I can replicate for all of the other templates. 
![image](https://github.com/user-attachments/assets/62ae654d-7bee-4fc5-a78a-1806ad650792)![image](https://github.com/user-attachments/assets/ec33fced-350b-41a8-82d1-234566712268)

**Comment by codextiny** [comment]
@shannonbaldwin 

we have checked the template, we didnt add any space from top/bottom, its basically gmail's behavior , unfortunately we can't do anything here ...

**Comment by shannonbaldwin** [comment]
@codextiny I think the best way to avoid this issue is to add a border to the template and remove grey background to make white. Can you let me know how long it would take to do this for one template and if it would be easy for me to copy that snippet to all other templates? You can test in this same template: Template ID: d-cd32f2e7f8e1463f94814b2a3c7ec5ca, "Untitled Version"


[See Figma design ](https://www.figma.com/design/QLGkG5qoUxg1586FMw7SYG/Pro-Invitation-Email-Templates-%7C-For-Dev?node-id=90-848&t=qUZiqcQBKb9WgDlp-4)

**Comment by codextiny** [comment]
@shannonbaldwin 

made changes according to figma, please check .

**Comment by shannonbaldwin** [comment]
@codextiny I updated the border color in Figma. Can you provide screenshot of where to update the color for this so I can test if needed? Also, the outline in figma has a border radius that I do not see in the template.

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/272390dc-ba2a-455e-8e3e-8f25b193b75c)
you can change border color from table styles, please see screenshot.

and border radius doesn't work on table and table tags...

**Comment by shannonbaldwin** [comment]
@codextiny Please adjust the border settings to where inner sections does not have extra spacing on the sides. This should do it. Please let me know how to update these for all templates. When you start working on onboarding templates, we will use this same border. 
![image](https://github.com/user-attachments/assets/02cd448a-0faf-4b65-9e77-54d5f22d035a)

**Comment by codextiny** [comment]
@shannonbaldwin 

multiple things need to be adjusted to make content stick to left/right, because there is table width, side spacing and both width and side spacing applied on multiple tables. so its difficult to give you screenshot of specific code where you can change and apply on other template because every template have multiple tables. hope you understand our point.

Thanks

**Comment by shannonbaldwin** [comment]
@codextiny ok, can you please update this template and then we can discuss pricing to update other campaigns that we have already done.

**Comment by codextiny** [comment]
@shannonbaldwin 

Done, please check

**Comment by shannonbaldwin** [comment]
@codextiny Looks good!
