### ISSUE TITLE
Onboarding Templates: V1 Live inHere

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#37]
@codextiny

**Set Up Profile Campaign** 
Please see [google doc ](https://docs.google.com/document/d/18ICM72zwi_4RuV8QG8b6wbodxOs4_sMQBgcSIWGy9ak/edit?usp=sharing)with content and highlighted variables needed. 

I copied a template from the pro invitation campaign to start template 1 of this series. See below for changes to that template that we can then copy over for formatting for the other 3 emails. 

Template ID for the new copy I made: d-a5c18593e33d41518e5d2bfa1cb6dd0e (labeled "Activate your account")
1. Remove CTA with "no thanks, I'm not interested
2. Remove code for signature block with loan officer and real estate names. We do not need them for this particular campaign. 
3. Decrease spacing under Activate account CTA. 
![image](https://github.com/user-attachments/assets/5bc9db3a-9a86-4dfd-aac2-7d154f4a059a)![image](https://github.com/user-attachments/assets/0c1cd7cd-45ea-48bb-8c86-7d97ba574cda)
![image](https://github.com/user-attachments/assets/4282214c-3799-463e-9d04-6a2f1eb7a29b)

**Comment by codextiny** [comment]
@shannonbaldwin 

We have fixed all three mentioned points, please check .

**Comment by shannonbaldwin** [comment]
@codextiny I dont think the changes saved. It still looks the same.

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/a6657c62-f189-46a4-b2a5-437f182a22d5)

its working for us, can you please refresh the page, we just updated the the points you mentioned above, didn't check google docs yet ...

**Comment by shannonbaldwin** [comment]
@codextiny Thank you! We just need to move the content box up that is filled with the grey to decrease that spacing between content and header since we will not have headlines on this email series.
![image](https://github.com/user-attachments/assets/3894a0c4-8fbe-4aff-b1e4-fb8af5dfdb48)

**Comment by codextiny** [comment]
@shannonbaldwin 

We have reduced the spacing, please check.
