### ISSUE TITLE
Update template design to include border

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#38]
@codextiny 

1. Template ID: d-cd32f2e7f8e1463f94814b2a3c7ec5ca 

"Untitled Version" (BORDER ALREADY COMPLETE BY CODEXTINY)

2. Template ID: d-8af666b64bac468e8ac15e9c87355b48
"Reminder - 24 hours"

3.Template ID: d-4f4eff1294474c7aa65e4335cbc5f28e 
"Reminder 2 - 48 hours"

4.Template ID: d-4469d6d9e8c44637a9e24a843d6f608c 
"Reminder 3 - 96 hours"

**Comment by shannonbaldwin** [comment]
@codextiny

Please update borders in this campaign next: Homeowner Introduction Campaign, Templates 1-17. There is only one instance in SendGrid of each so should be easy to find. 

The first template ID is Template ID: d-afd97d3a77384a68bf05700e6aecb503 for reference.

**Comment by shannonbaldwin** [comment]
@codextiny 

Please update borders in this campaign next: Pro Invitation V2.3 ONLY, Templates 1-9

1 | d-0d7dd5c33f794217a3bbf3200b04ddb2
2 | d-f6bfb7262b3043d6a9d72a9f7ed591a5
3 |  d-304ae56afac848949e1991a6fe76ef54
4 | d-b5dc6d1c3a724ed3a9ebba6658aa73eb
5 | d-e20cfe0da3f5488bb7d1bf5691205f00
6 |  d-400e486102fc45dc8b5a36611cf754a6
7 |  d-69f491a3e688416ba95bc59069f020a5
8 | d-87b1c874c29a4410bf3656a37471128d
9 | d-63700940fc3c447e9233187ccb14805f

**Comment by codextiny** [comment]
@shannonbaldwin 

please attach final figma with border color here for reference

**Comment by shannonbaldwin** [comment]
https://www.figma.com/design/QLGkG5qoUxg1586FMw7SYG/Pro-Invitation-Email-Templates-%7C-For-Dev?node-id=113-495&t=EgVZD6KTHB5rKuO2-4

**Comment by codextiny** [comment]
@shannonbaldwin 

We have updated border style on all templates, please check
