### ISSUE TITLE
Text Color Displaying Different Across Devices

### ISSUE THREAD

**Issue by NedHOAI** [shannonbaldwin/Litmus-SG-Project#4]
Two versions of the test message were sent from Sendgrid. 
For Shannon, this image was not solid black:
![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/174059892/67413877-0aba-4c43-9ced-81ff1a131ef2)

For Ned, this image was solid black:
![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/174059892/9b653520-6ebc-43bd-96f5-22507e1ec653)

Expected:
Color for this basic text should be consistent across providers.

**Comment by codextiny** [comment]
@NedHOAI 

We have checked, color was missing in code, now we have applied color exact like figma. Hopefully it will work fine now.

Thanks
