### ISSUE TITLE
Removing logo from header and centering variable 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#40]
@codextiny Can you please make a copy of template Template ID: d-afd97d3a77384a68bf05700e6aecb503 and remove the top left logo variable and center the hub address variable to the template (both top to bottom and left to right)? We are doing final testing and we may want to remove all of these in the templates, depending on how it looks.
![image](https://github.com/user-attachments/assets/da3c4591-b5ec-4749-964d-680fcc293866)

**Comment by codextiny** [comment]
@shannonbaldwin 

Done, please check
