### ISSUE TITLE
Add New Signature Block Design to 4 templates

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#42]
@codextiny Can you please apply the new signature block to the existing templates below? There will only be one person which you will see in the existing template.

Template ID: d-cd32f2e7f8e1463f94814b2a3c7ec5ca
"Untitled Version" 

Template ID: d-8af666b64bac468e8ac15e9c87355b48
"Reminder - 24 hours"
3.Template ID: d-4f4eff1294474c7aa65e4335cbc5f28e
"Reminder 2 - 48 hours"

4.Template ID: d-4469d6d9e8c44637a9e24a843d6f608c
"Reminder 3 - 96 hours"
![image](https://github.com/user-attachments/assets/4b01ff3f-9f91-43ca-b7f0-826bb88e2935)

**Comment by codextiny** [comment]
@shannonbaldwin 

for current templates, there are all conditions based on pro_full_name but new signatures are based on real estate and loan officer so what should we do ...? 

![image](https://github.com/user-attachments/assets/c9a327a2-7409-4deb-8c7a-84c94bf8c5a2)

**Comment by codextiny** [comment]
we will copy/paste the new layout and change to content, or you want us to change the conditions as well, means replace conditions with pro_full_name ??

**Comment by shannonbaldwin** [comment]
@codextiny Please update the new layout of signature block with the existing conditions you highlighted above, i.e. pro full name, pro mls, pro email, etc.

**Comment by codextiny** [comment]
@shannonbaldwin 

d-cd32f2e7f8e1463f94814b2a3c7ec5ca

We have replaced the current layout with new one with existing conditions, please check then we will move this on other templates.

Thanks

**Comment by shannonbaldwin** [comment]
@codextiny I copied them over and they seem to work. Can you do a quick check to make sure?

**Comment by codextiny** [comment]
@shannonbaldwin 

Yup, everything looks great.
