### ISSUE TITLE
onboarding templates

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#45]
@codextiny
Template ID: d-a5c18593e33d41518e5d2bfa1cb6dd0e | V1

1. This was an error I found  before I made any adjustments.
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/2d6238ee-a57f-4e73-9cec-df12e49498df">

2. I adjusted the width given we do not have hero images. Can you ensure all other areas are adjusted that need to be?
![image](https://github.com/user-attachments/assets/753cde68-29bf-4439-aab5-29ebc16bd3b4)

3. I adjusted padding in certain areas. Can you please decrease this spacing here?![image](https://github.com/user-attachments/assets/c28eae24-4c0a-4e83-a9ab-7df0cb5374a1)

**Comment by shannonbaldwin** [comment]
@codextiny 
Template ID: d-a5c18593e33d41518e5d2bfa1cb6dd0e | V2

1. Found this error![image](https://github.com/user-attachments/assets/b2a483fc-b9ad-4da5-9c14-bcf974f11bea)
2. Please adjust width to match V1 and all other templates in this onboarding campaign you developed.
3. Please add gray line on all templates above the bottom logo like V1.
![image](https://github.com/user-attachments/assets/3cecbe36-ae5d-4be0-b8c5-524665a2b378)

**Comment by shannonbaldwin** [comment]
@codextiny
Template ID: Template ID: d-93c6fe42d8fa4564918217b687dd9d4d  | **V1 and V2**
https://github.com/shannonbaldwin/Litmus-SG-Project/issues/45#issuecomment-2274060201

**Comment by shannonbaldwin** [comment]
@codextiny
Template ID: d-12a2ea1b2eb24edeba7ea0d698903835 

1. Please adjust width to match V1 and all other templates in this onboarding campaign you developed.
2.![image](https://github.com/user-attachments/assets/a484f6de-1172-4ae3-a5c6-f36eea37cd8f)
3. Logo in footer should match max and min size as header logo (160x57). Please update in all templates (I did a few).

**Comment by shannonbaldwin** [comment]
@codextiny 
Template ID: d-9ca3796729454f1ebe846db369eb8ae4 | **V1 and V2**

1. First name needs to be on seperate line like the other templates.![image](https://github.com/user-attachments/assets/366f420c-fbab-4dc5-bf00-b6e2b229941c)

**Comment by shannonbaldwin** [comment]
@codextiny 
Template ID: d-f9603a75ae3547708544f842dc458953 | V1

 Incorrect content.

**Comment by shannonbaldwin** [comment]
Template ID: d-f9603a75ae3547708544f842dc458953 | V2

Spacing is inconsistent. Please match last two paragraphs with spacing under paragraph![image](https://github.com/user-attachments/assets/267c67f4-c6ca-4714-b1a9-e0a2be9e66dd)

**Comment by codextiny** [comment]
> d-a5c18593e33d41518e5d2bfa1cb6dd0e

![image](https://github.com/user-attachments/assets/1d2daf20-30e8-4a94-8ddf-817d786479c1)

Rest of points done.

**Comment by codextiny** [comment]
> @codextiny Template ID: d-a5c18593e33d41518e5d2bfa1cb6dd0e | V1
> 
>     1. This was an error I found  before I made any adjustments.
> 
> 
> <img alt="image" width="1315" src="https://private-user-images.githubusercontent.com/167017886/355933178-2d6238ee-a57f-4e73-9cec-df12e49498df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTg2MTEsIm5iZiI6MTcyMzA1ODMxMSwicGF0aCI6Ii8xNjcwMTc4ODYvMzU1OTMzMTc4LTJkNjIzOGVlLWE1N2YtNGU3My05Y2VjLWRmMTJlNDk0OThkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTE4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTViNDZkMjMwNjVhMjk0M2FkZjk2YWU0ZmQ2MDA1YTg5YTM1ZWI2ZDBlMzBjYzc1MjVkOTVkYjZjNmYzZjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YblX80t2cM15xdUyCzB3T5xzS3AsTbWJ8dleY53TlNs">
> 
>     2. I adjusted the width given we do not have hero images. Can you ensure all other areas are adjusted that need to be?
>        ![image](https://private-user-images.githubusercontent.com/167017886/355933809-753cde68-29bf-4439-aab5-29ebc16bd3b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTg2MTEsIm5iZiI6MTcyMzA1ODMxMSwicGF0aCI6Ii8xNjcwMTc4ODYvMzU1OTMzODA5LTc1M2NkZTY4LTI5YmYtNDQzOS1hYWI1LTI5ZWJjMTZiZDNiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTE4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODA3YTI5YzI4ZGY5MDY2NWQ4NGM2MjU4NzBmNWRmNjJhNTAyN2VkMDcyMWFjNmY5N2Y5ZmZkMDY0YTE1MGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fK3-Ztbgir5Yj1I6jGFQny4lVuPpl9tSQPkicSdW5oA)
> 
>     3. I adjusted padding in certain areas. Can you please decrease this spacing here?![image](https://private-user-images.githubusercontent.com/167017886/355934089-c28eae24-4c0a-4e83-a9ab-7df0cb5374a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTg2MTEsIm5iZiI6MTcyMzA1ODMxMSwicGF0aCI6Ii8xNjcwMTc4ODYvMzU1OTM0MDg5LWMyOGVhZTI0LTRjMGEtNGU4My1hOWFiLTdkZjBjYjUzNzRhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTE4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWZjYjQ1N2VkMTFmM2I1Yjc4NDY2YzI4ZDk3ODVjZjgzMGEzOWFjZGYxMjczM2EyZWUwNzBjYjQ1ZmM5Y2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LKvbqvOp70yDfNR9LJNNwfAORUzAUoYV_4q6hWe5o80)


![image](https://github.com/user-attachments/assets/1d2daf20-30e8-4a94-8ddf-817d786479c1)

Rest of points are done.

**Comment by codextiny** [comment]
> @codextiny Template ID: d-a5c18593e33d41518e5d2bfa1cb6dd0e | V1
> 
>     1. This was an error I found  before I made any adjustments.
> 
> 
> <img alt="image" width="1315" src="https://private-user-images.githubusercontent.com/167017886/355933178-2d6238ee-a57f-4e73-9cec-df12e49498df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTg3MjQsIm5iZiI6MTcyMzA1ODQyNCwicGF0aCI6Ii8xNjcwMTc4ODYvMzU1OTMzMTc4LTJkNjIzOGVlLWE1N2YtNGU3My05Y2VjLWRmMTJlNDk0OThkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTIwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjAxYTkxZTE5OWU4NjkzNWUyNTNlYjVjZjZhMjQ2OWE2NDYyNjFhYTA3NmI3NGQ2NTIyMDFiNzVkMTgyMmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EJL3a146bEB3KpTsjsIINY3gLOajzHvF6aaC2e2sxkY">
> 
>     2. I adjusted the width given we do not have hero images. Can you ensure all other areas are adjusted that need to be?
>        ![image](https://private-user-images.githubusercontent.com/167017886/355933809-753cde68-29bf-4439-aab5-29ebc16bd3b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTg3MjQsIm5iZiI6MTcyMzA1ODQyNCwicGF0aCI6Ii8xNjcwMTc4ODYvMzU1OTMzODA5LTc1M2NkZTY4LTI5YmYtNDQzOS1hYWI1LTI5ZWJjMTZiZDNiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTIwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzYyNzg0MTFjZDA2Y2UyMjliNzMwNDI1ZTJhNzlkZmY4MDdjNGNlZjA2N2VhMWRlMWI1YTIxOTAzZDI3MTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.snjM4wF_jS4fa13dMLlgMGRVIkyQrPGXmjxmzZvkZ8Q)
> 
>     3. I adjusted padding in certain areas. Can you please decrease this spacing here?![image](https://private-user-images.githubusercontent.com/167017886/355934089-c28eae24-4c0a-4e83-a9ab-7df0cb5374a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTg3MjQsIm5iZiI6MTcyMzA1ODQyNCwicGF0aCI6Ii8xNjcwMTc4ODYvMzU1OTM0MDg5LWMyOGVhZTI0LTRjMGEtNGU4My1hOWFiLTdkZjBjYjUzNzRhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTIwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjE5MDg2M2YyNDExMGExZDMzMDQwYzM0NWU4OWM1NTNjMDIxZGUyNDI1MmJkZTJjMmE5NTQ1YjIzNjYwYzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dJ0z44fR2-2r7DsR7JPRN2Cyh7ERFHpkI28hd7VEVSc)

1. This was an error I found before I made any adjustments.
Done

2. I adjusted the width given we do not have hero images. Can you ensure all other areas are adjusted that need to be?
You have missed some widths, every table's max-width needs to be adjusted accordingly .
![image](https://github.com/user-attachments/assets/2be7cde6-e2af-4a1c-ab6d-bc6867759a6e)

3. I adjusted padding in certain areas. Can you please decrease this spacing here?
![image](https://github.com/user-attachments/assets/1d2daf20-30e8-4a94-8ddf-817d786479c1)
Our suggestion, you have to get basic knowledge of html, css to make changes like this, other wise it will become messy and time taking for you.

**Comment by codextiny** [comment]
@shannonbaldwin 

d-a5c18593e33d41518e5d2bfa1cb6dd0e - V1

is it correct one to copy width, background, top border of bottom logo to other templates ??

please respond asap...

**Comment by shannonbaldwin** [comment]
@codextiny Yes, same for all 4 of these templates in the onboarding campaign.

**Comment by codextiny** [comment]
@shannonbaldwin 

above points are done please check.

**Comment by shannonbaldwin** [comment]
@codextiny Template ID: d-9ca3796729454f1ebe846db369eb8ae4 


**V1 and V2:** Please adjust line spacing in paragraph 1 to match paragraph 2
![image](https://github.com/user-attachments/assets/4c54a064-f40c-4450-b9d0-0e16f45b0d89)

**Comment by shannonbaldwin** [comment]
@codextiny For ALL 5 templates, please remove this text only but keep the spacing as is. 
![image](https://github.com/user-attachments/assets/020f5384-6b67-4cef-832a-ac1c2f5b290f)

**Comment by codextiny** [comment]
@shannonbaldwin 

Done, please check

**Comment by shannonbaldwin** [comment]
@codextiny Template ID: d-a5c18593e33d41518e5d2bfa1cb6dd0e 

This template still has the "Questions.." text.

**Comment by codextiny** [comment]
@shannonbaldwin 

done, please check

**Comment by shannonbaldwin** [comment]
@codextiny Thank you.
