### ISSUE TITLE
Onboarding templates - mobile view 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#48]
@codextiny 

Please see broken mobile view in all of the onboarding templates (campaigns #1 - #5)[ in this doc](https://docs.google.com/document/d/1ejPx4qxN7HrtN3H67UYeUh0T9cNr9MbWaV95bMThWOE/edit?usp=sharing) (see IDs).

<img width="377" alt="image" src="https://github.com/user-attachments/assets/03ca6779-930e-4b7c-ab14-48e7a1d58053">

**Comment by codextiny** [comment]
@shannonbaldwin 

fixed on all templates, please check
