### ISSUE TITLE
Update Font Color in Template

### ISSUE THREAD

**Issue by NedHOAI** [shannonbaldwin/Litmus-SG-Project#5]
In previews, the Sendgrid template is hard to read with current font colors.
The Figma file has been updated with a new font color for improved readability:
https://www.figma.com/design/Nbc8bDKXEgxkfXHCGmqEFC/email-marketing?node-id=1223-42&t=Abd2qGvlEhX88FDD-4

**Comment by codextiny** [comment]
@NedHOAI 

updated font color in sendgrid template according to figma, please check.
