### ISSUE TITLE
Add Line Break in Copy

### ISSUE THREAD

**Issue by NedHOAI** [shannonbaldwin/Litmus-SG-Project#6]
The ending body section was center adjusted; this has been left adjusted in the Sengrid template. However, we need to add a line break to this section, as displayed in the screenshot:

![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/174059892/a8b45e95-4063-4c73-b39e-5d09543bded9)

**Comment by codextiny** [comment]
@NedHOAI 

adjusted in sendgrid, please check an let us know if you have any issue .

Thanks

**Comment by shannonbaldwin** [comment]
@codextiny We still need another line break here.

**Comment by codextiny** [comment]
@shannonbaldwin 

Added please check.

**Comment by NedHOAI** [comment]
@codextiny they are back on single lines, but there is still no break between them.

This currently reads:
"Your homeowner portal is ready! Simply click the button below to get started.
No fees apply. This is a gift courtesy of {{pro_full_name}}."

It should read:
"Your homeowner portal is ready! Simply click the button below to get started.

No fees apply. This is a gift courtesy of {{pro_full_name}}."

**Comment by codextiny** [comment]
@NedHOAI 

![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/113863175/6c357447-013a-459b-b333-a570b0b8a359)

Added space, please refresh the page and check again.
