### ISSUE TITLE
Adjust color of Opt Out Text

### ISSUE THREAD

**Issue by NedHOAI** [shannonbaldwin/Litmus-SG-Project#7]
The Opt Out text below the Log In button needs to match the color of the body text. See screenshot for reference:
![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/174059892/3d9b051c-58fc-4c0d-b7e0-37b91e4b24e0)

**Comment by codextiny** [comment]
@NedHOAI 

adjusted, please check
