### ISSUE TITLE
Updated Details in SendGrid

### ISSUE THREAD

**Issue by NedHOAI** [shannonbaldwin/Litmus-SG-Project#8]
The following changes were made in SendGrid. They were NOT adjusted in Litmus:

- When organisation_logo_simple was missing from the test data, it made an odd space for the upper left corner. I added an #if check to bracket it. This should prevent it from having an odd display if there's no data in the payload.
- On the button color, I added a text snippet that dynamically controls the button color. This should help us distribute this to additional SendGrid instances that need specific white labeling.
- The org logo in the footer was pretty big. The one in the header is restricted to 180x100; I did something similar in the footer and enforced a max-height and max-width on it.
- I added a new variable - {{hub_organisation_address}} to the test payload data. This is being built currently by dev and should allow us to white label this across instances with greater ease.
- Additionally, I added this variable to the footer in place of the hardcoded address.

**Comment by codextiny** [comment]
@NedHOAI 

in which sendgrid template you have made all these changes, can you please mention the name here ??

**Comment by NedHOAI** [comment]
@codextiny d-f9aa0a07032541beb5b707bcf800c2b6

**Comment by codextiny** [comment]
@NedHOAI 

we have read all the points which you have mentioned above, these are all related to the sendgrid because litmus doesn't support variables and conditions ..

Thanks
