### ISSUE TITLE
Preview Text Missing

### ISSUE THREAD

**Issue by NedHOAI** [shannonbaldwin/Litmus-SG-Project#9]
The template in Sendgrid is currently missing Preview Text:
d-f9aa0a07032541beb5b707bcf800c2b6

Each email needs to have a preview text to accompany it's subject text. Please add the necessary text to display a preview text for email clients.

**Comment by codextiny** [comment]
@NedHOAI 

Already added preview text, see in screenshot.

![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/113863175/023c7d51-e00d-4ab4-bb7e-5bf1b2aff592)

please check and let us know if its not working .

**Comment by NedHOAI** [comment]
@codextiny That is the subject, not the preview text. 

The preview text is a hidden piece of text inside the body of the email. It is not visible when viewing the email directly, but is picked up by email clients when parsing emails. This is a very common method of adding additional context to the subject line of an email with content that is not in the body of the email itself.

Here is a guide: https://www.litmus.com/blog/the-ultimate-guide-to-preview-text-support

**Comment by codextiny** [comment]
@NedHOAI 

Added preview text in both sendgrid and litmus.
Please check .

Thanks

**Comment by NedHOAI** [comment]
Thank you, this looks good.
